name: ci

on: push

jobs:
  test:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: test-matrix
    steps:
      - if: ${{ needs.test-matrix.result != 'success' }}
        run: exit 1
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.4, 1.11.2]
        otp: [22, 23]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build/test
            !_build/test/lib/ex_persona
          key: mix-cache-v0-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only test

      - run: mix ci.test
